#!/usr/bin/env bash

STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=5.4 ENABLE_MCRYPT=0 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=5.4 ENABLE_MCRYPT=1 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=5.5 ENABLE_MCRYPT=0 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=5.5 ENABLE_MCRYPT=1 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=5.6 ENABLE_MCRYPT=0 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=5.6 ENABLE_MCRYPT=1 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=7.0 ENABLE_MCRYPT=0 ./tests/run-tests.sh
STATHAT_API_KEY=1cvNhtUFGo0bMuff TRAVIS_BUILD_DIR=`pwd` PHP_VERSION=7.0 ENABLE_MCRYPT=1 ./tests/run-tests.sh
